CREATE DATABASE IF NOT EXISTS lankin;
USE lankin;

-- CREATE TABLE article
-- (id INT PRIMARY KEY AUTO_INCREMENT,
--  author VARCHAR(75) NOT NULL,
--  title VARCHAR(120) NOT NULL,
--  body VARCHAR(255)
-- );

CREATE TABLE author
(author_id INT PRIMARY KEY AUTO_INCREMENT,
 firstName VARCHAR(120) NOT NULL,
 lastName VARCHAR(120) NOT NULL,
 `description` VARCHAR(255)
);

CREATE TABLE article
(id INT PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR(120) NOT NULL,
 body VARCHAR(255),
 FOREIGN KEY (id) REFERENCES author(author_id)
);