version: '2.1'
services:
  database:
    image: mysql
#    container_name: lankindb
    container_name: localhost:3306
    environment:
      - MYSQL_ROOT_PASSWORD=M1xV1n1l
      - MYSQL_DATABASE=lankin
    volumes:
      - datavolume:/var/lib/mysql
    ports:
      - 8080:3306
    healthcheck:
      test: "exit 0"

  restful:
    build: .
    image: restful
    container_name: restful
    restart: on-failure
    environment:
      MYSQL_DATABASE_HOST: database
    depends_on:
      database:
        condition: service_healthy

volumes:
  datavolume:

#docker build -t restful .
#docker-compose up --build
#docker-compose down -v

#  curl -X POST -H 'Content-Type:application/json' http://localhost:8080/article -d '{"author":"author","title":"title","body":"body from docker"}'
#  curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://localhost:8080/services
