version: '2.1'
services:
  database:
    image: mysql
    container_name: lankin-db
    environment:
      - MYSQL_ROOT_PASSWORD=M1xV1n1l
      - MYSQL_DATABASE=lankin
    volumes:
      - datavolume:/var/lib/mysql
    ports:
      - 8080:3306
    healthcheck:
      test: "exit 0"

  restful:
    build: .
    image: restful
    container_name: restful
    restart: on-failure
    environment:
      MYSQL_DATABASE_HOST: database
    depends_on:
      database:
        condition: service_healthy

volumes:
  datavolume:


