version: "3.8"
services:

#--DB--
  mysql:
    container_name: lankindb
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - restful-mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=M1xV1n1l
      - MYSQL_DATABASE=lankin

#--WEB>--
  restful:
    build: .
    image: restful
    ports:
      - "8080:8080"
    restart: always
    networks:
      - restful-mysql-network
    depends_on:
      - mysql
    links:
      - mysql
      -
#--Prop--
networks:
  restful-mysql-network:
volumes:
  db_data: { }


#docker build -t restful .
#docker-compose up --build
#docker-compose down -v
#  docker exec -it <container Id> <comand>
#  curl -X POST -H 'Content-Type:application/json' http://localhost:8080/article -d '{"author":"author","title":"title","body":"body from docker"}'
#  curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://localhost:8080/services

#-------------n
  ------------------------------------
#version: '3.8'
#services:
#  database:
#    image: mysql
#    container_name: lankindb
#    environment:
#      - MYSQL_ROOT_PASSWORD=M1xV1n1l
#      - MYSQL_DATABASE=lankin
#    volumes:
#      - datavolume:/var/lib/mysql
#
#  restful:
#    build: .
#    image: restful
#    container_name: restful
#    ports:
#      - 8080:8080
#    restart: on-failure
#    environment:
#      MYSQL_DATABASE_HOST: database
#    depends_on:
#      - database
#    links:
#      - database
#
#volumes:
#  datavolume:
#----------------------------------------------------